# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_glf', [dirname(__file__)])
        except ImportError:
            import _glf
            return _glf
        if fp is not None:
            try:
                _mod = imp.load_module('_glf', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _glf = swig_import_helper()
    del swig_import_helper
else:
    import _glf
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def glfGet3DSolidStringTriangles(s):
    return _glf.glfGet3DSolidStringTriangles(s)
glfGet3DSolidStringTriangles = _glf.glfGet3DSolidStringTriangles

_glf.solid_swigconstant(_glf)
solid = _glf.solid

_glf.solid3d_swigconstant(_glf)
solid3d = _glf.solid3d

_glf.wire_swigconstant(_glf)
wire = _glf.wire

_glf.wire3d_swigconstant(_glf)
wire3d = _glf.wire3d

def glfDrawLabels(coordinates, labels, indices, billboardmat, fontTranslation, fontRotateAngles, fontTypeIsVector, fontScales, style, frontMaterial=0, frontAndBack=0, labelTrans=None, backMaterial=0, frontMatBind=0, backMatBind=0):
    return _glf.glfDrawLabels(coordinates, labels, indices, billboardmat, fontTranslation, fontRotateAngles, fontTypeIsVector, fontScales, style, frontMaterial, frontAndBack, labelTrans, backMaterial, frontMatBind, backMatBind)
glfDrawLabels = _glf.glfDrawLabels

_glf.GLF_ERROR_swigconstant(_glf)
GLF_ERROR = _glf.GLF_ERROR

_glf.GLF_OK_swigconstant(_glf)
GLF_OK = _glf.GLF_OK

_glf.GLF_YES_swigconstant(_glf)
GLF_YES = _glf.GLF_YES

_glf.GLF_NO_swigconstant(_glf)
GLF_NO = _glf.GLF_NO

_glf.GLF_CONSOLE_MESSAGES_swigconstant(_glf)
GLF_CONSOLE_MESSAGES = _glf.GLF_CONSOLE_MESSAGES

_glf.GLF_TEXTURING_swigconstant(_glf)
GLF_TEXTURING = _glf.GLF_TEXTURING

_glf.GLF_CONTOURING_swigconstant(_glf)
GLF_CONTOURING = _glf.GLF_CONTOURING

_glf.GLF_LEFT_UP_swigconstant(_glf)
GLF_LEFT_UP = _glf.GLF_LEFT_UP

_glf.GLF_LEFT_CENTER_swigconstant(_glf)
GLF_LEFT_CENTER = _glf.GLF_LEFT_CENTER

_glf.GLF_LEFT_DOWN_swigconstant(_glf)
GLF_LEFT_DOWN = _glf.GLF_LEFT_DOWN

_glf.GLF_CENTER_UP_swigconstant(_glf)
GLF_CENTER_UP = _glf.GLF_CENTER_UP

_glf.GLF_CENTER_CENTER_swigconstant(_glf)
GLF_CENTER_CENTER = _glf.GLF_CENTER_CENTER

_glf.GLF_CENTER_DOWN_swigconstant(_glf)
GLF_CENTER_DOWN = _glf.GLF_CENTER_DOWN

_glf.GLF_RIGHT_UP_swigconstant(_glf)
GLF_RIGHT_UP = _glf.GLF_RIGHT_UP

_glf.GLF_RIGHT_CENTER_swigconstant(_glf)
GLF_RIGHT_CENTER = _glf.GLF_RIGHT_CENTER

_glf.GLF_RIGHT_DOWN_swigconstant(_glf)
GLF_RIGHT_DOWN = _glf.GLF_RIGHT_DOWN

_glf.GLF_CENTER_swigconstant(_glf)
GLF_CENTER = _glf.GLF_CENTER

_glf.GLF_LEFT_swigconstant(_glf)
GLF_LEFT = _glf.GLF_LEFT

_glf.GLF_RIGHT_swigconstant(_glf)
GLF_RIGHT = _glf.GLF_RIGHT

_glf.GLF_UP_swigconstant(_glf)
GLF_UP = _glf.GLF_UP

_glf.GLF_DOWN_swigconstant(_glf)
GLF_DOWN = _glf.GLF_DOWN

_glf.GLF_CONSOLE_CURSOR_swigconstant(_glf)
GLF_CONSOLE_CURSOR = _glf.GLF_CONSOLE_CURSOR

def glfInit():
    return _glf.glfInit()
glfInit = _glf.glfInit

def glfClose():
    return _glf.glfClose()
glfClose = _glf.glfClose

def glfLoadFont(font_name):
    return _glf.glfLoadFont(font_name)
glfLoadFont = _glf.glfLoadFont

def glfLoadBMFFont(FName):
    return _glf.glfLoadBMFFont(FName)
glfLoadBMFFont = _glf.glfLoadBMFFont

def glfUnloadFont():
    return _glf.glfUnloadFont()
glfUnloadFont = _glf.glfUnloadFont

def glfUnloadBMFFont():
    return _glf.glfUnloadBMFFont()
glfUnloadBMFFont = _glf.glfUnloadBMFFont

def glfUnloadFontD(font_descriptor):
    return _glf.glfUnloadFontD(font_descriptor)
glfUnloadFontD = _glf.glfUnloadFontD

def glfUnloadBMFFontD(bmf_descriptor):
    return _glf.glfUnloadBMFFontD(bmf_descriptor)
glfUnloadBMFFontD = _glf.glfUnloadBMFFontD

def glfDrawWiredSymbol(s):
    return _glf.glfDrawWiredSymbol(s)
glfDrawWiredSymbol = _glf.glfDrawWiredSymbol

def glfDrawWiredString(s):
    return _glf.glfDrawWiredString(s)
glfDrawWiredString = _glf.glfDrawWiredString

def glfDrawSolidSymbol(s):
    return _glf.glfDrawSolidSymbol(s)
glfDrawSolidSymbol = _glf.glfDrawSolidSymbol

def glfDrawSolidString(s):
    return _glf.glfDrawSolidString(s)
glfDrawSolidString = _glf.glfDrawSolidString

def glfDraw3DWiredSymbol(s):
    return _glf.glfDraw3DWiredSymbol(s)
glfDraw3DWiredSymbol = _glf.glfDraw3DWiredSymbol

def glfDraw3DWiredString(s):
    return _glf.glfDraw3DWiredString(s)
glfDraw3DWiredString = _glf.glfDraw3DWiredString

def glfDraw3DSolidSymbol(s):
    return _glf.glfDraw3DSolidSymbol(s)
glfDraw3DSolidSymbol = _glf.glfDraw3DSolidSymbol

def glfDraw3DSolidString(s):
    return _glf.glfDraw3DSolidString(s)
glfDraw3DSolidString = _glf.glfDraw3DSolidString

def glfStartBitmapDrawing():
    return _glf.glfStartBitmapDrawing()
glfStartBitmapDrawing = _glf.glfStartBitmapDrawing

def glfStopBitmapDrawing():
    return _glf.glfStopBitmapDrawing()
glfStopBitmapDrawing = _glf.glfStopBitmapDrawing

def glfDrawBSymbol(s):
    return _glf.glfDrawBSymbol(s)
glfDrawBSymbol = _glf.glfDrawBSymbol

def glfDrawBString(s):
    return _glf.glfDrawBString(s)
glfDrawBString = _glf.glfDrawBString

def glfDrawBMaskSymbol(s):
    return _glf.glfDrawBMaskSymbol(s)
glfDrawBMaskSymbol = _glf.glfDrawBMaskSymbol

def glfDrawBMaskString(s):
    return _glf.glfDrawBMaskString(s)
glfDrawBMaskString = _glf.glfDrawBMaskString

def glfDrawWiredSymbolF(font_descriptor, s):
    return _glf.glfDrawWiredSymbolF(font_descriptor, s)
glfDrawWiredSymbolF = _glf.glfDrawWiredSymbolF

def glfDrawWiredStringF(font_descriptor, s):
    return _glf.glfDrawWiredStringF(font_descriptor, s)
glfDrawWiredStringF = _glf.glfDrawWiredStringF

def glfDrawSolidSymbolF(font_descriptor, s):
    return _glf.glfDrawSolidSymbolF(font_descriptor, s)
glfDrawSolidSymbolF = _glf.glfDrawSolidSymbolF

def glfDrawSolidStringF(font_descriptor, s):
    return _glf.glfDrawSolidStringF(font_descriptor, s)
glfDrawSolidStringF = _glf.glfDrawSolidStringF

def glfDraw3DWiredSymbolF(font_descriptor, s):
    return _glf.glfDraw3DWiredSymbolF(font_descriptor, s)
glfDraw3DWiredSymbolF = _glf.glfDraw3DWiredSymbolF

def glfDraw3DWiredStringF(font_descriptor, s):
    return _glf.glfDraw3DWiredStringF(font_descriptor, s)
glfDraw3DWiredStringF = _glf.glfDraw3DWiredStringF

def glfDraw3DSolidSymbolF(font_descriptor, s):
    return _glf.glfDraw3DSolidSymbolF(font_descriptor, s)
glfDraw3DSolidSymbolF = _glf.glfDraw3DSolidSymbolF

def glfDraw3DSolidStringF(font_descriptor, s):
    return _glf.glfDraw3DSolidStringF(font_descriptor, s)
glfDraw3DSolidStringF = _glf.glfDraw3DSolidStringF

def glfGetStringBoundsF(fd, s):
    return _glf.glfGetStringBoundsF(fd, s)
glfGetStringBoundsF = _glf.glfGetStringBoundsF

def glfGetStringBounds(s):
    return _glf.glfGetStringBounds(s)
glfGetStringBounds = _glf.glfGetStringBounds

def glfSetSymbolSpace(sp):
    return _glf.glfSetSymbolSpace(sp)
glfSetSymbolSpace = _glf.glfSetSymbolSpace

def glfGetSymbolSpace():
    return _glf.glfGetSymbolSpace()
glfGetSymbolSpace = _glf.glfGetSymbolSpace

def glfSetSpaceSize(sp):
    return _glf.glfSetSpaceSize(sp)
glfSetSpaceSize = _glf.glfSetSpaceSize

def glfGetSpaceSize():
    return _glf.glfGetSpaceSize()
glfGetSpaceSize = _glf.glfGetSpaceSize

def glfSetSymbolDepth(dpth):
    return _glf.glfSetSymbolDepth(dpth)
glfSetSymbolDepth = _glf.glfSetSymbolDepth

def glfGetSymbolDepth():
    return _glf.glfGetSymbolDepth()
glfGetSymbolDepth = _glf.glfGetSymbolDepth

def glfSetCurrentFont(Font_Descriptor):
    return _glf.glfSetCurrentFont(Font_Descriptor)
glfSetCurrentFont = _glf.glfSetCurrentFont

def glfSetCurrentBMFFont(Font_Descriptor):
    return _glf.glfSetCurrentBMFFont(Font_Descriptor)
glfSetCurrentBMFFont = _glf.glfSetCurrentBMFFont

def glfGetCurrentFont():
    return _glf.glfGetCurrentFont()
glfGetCurrentFont = _glf.glfGetCurrentFont

def glfGetCurrentBMFFont():
    return _glf.glfGetCurrentBMFFont()
glfGetCurrentBMFFont = _glf.glfGetCurrentBMFFont

def glfSetAnchorPoint(anchp):
    return _glf.glfSetAnchorPoint(anchp)
glfSetAnchorPoint = _glf.glfSetAnchorPoint

def glfSetContourColor(r, g, b, a):
    return _glf.glfSetContourColor(r, g, b, a)
glfSetContourColor = _glf.glfSetContourColor

def glfEnable(what):
    return _glf.glfEnable(what)
glfEnable = _glf.glfEnable

def glfDisable(what):
    return _glf.glfDisable(what)
glfDisable = _glf.glfDisable

def glfSetConsoleParam(width, height):
    return _glf.glfSetConsoleParam(width, height)
glfSetConsoleParam = _glf.glfSetConsoleParam

def glfSetConsoleFont(Font_Descriptor):
    return _glf.glfSetConsoleFont(Font_Descriptor)
glfSetConsoleFont = _glf.glfSetConsoleFont

def glfConsoleClear():
    return _glf.glfConsoleClear()
glfConsoleClear = _glf.glfConsoleClear

def glfPrint(s, lenght):
    return _glf.glfPrint(s, lenght)
glfPrint = _glf.glfPrint

def glfPrintString(s):
    return _glf.glfPrintString(s)
glfPrintString = _glf.glfPrintString

def glfPrintChar(s):
    return _glf.glfPrintChar(s)
glfPrintChar = _glf.glfPrintChar

def glfConsoleDraw():
    return _glf.glfConsoleDraw()
glfConsoleDraw = _glf.glfConsoleDraw

def glfSetCursorBlinkRate(Rate):
    return _glf.glfSetCursorBlinkRate(Rate)
glfSetCursorBlinkRate = _glf.glfSetCursorBlinkRate

def glfStringCentering(center):
    return _glf.glfStringCentering(center)
glfStringCentering = _glf.glfStringCentering

def glfGetStringCentering():
    return _glf.glfGetStringCentering()
glfGetStringCentering = _glf.glfGetStringCentering

def glfBitmapStringCentering(center):
    return _glf.glfBitmapStringCentering(center)
glfBitmapStringCentering = _glf.glfBitmapStringCentering

def glfBitmapGetStringCentering():
    return _glf.glfBitmapGetStringCentering()
glfBitmapGetStringCentering = _glf.glfBitmapGetStringCentering

def glfStringDirection(direction):
    return _glf.glfStringDirection(direction)
glfStringDirection = _glf.glfStringDirection

def glfGetStringDirection():
    return _glf.glfGetStringDirection()
glfGetStringDirection = _glf.glfGetStringDirection

def glfSetRotateAngle(angle):
    return _glf.glfSetRotateAngle(angle)
glfSetRotateAngle = _glf.glfSetRotateAngle

def glfSetBRotateAngle(angle):
    return _glf.glfSetBRotateAngle(angle)
glfSetBRotateAngle = _glf.glfSetBRotateAngle
# This file is compatible with both classic and new-style classes.

cvar = _glf.cvar

