# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_UTVolumeLibrary', [dirname(__file__)])
        except ImportError:
            import _UTVolumeLibrary
            return _UTVolumeLibrary
        if fp is not None:
            try:
                _mod = imp.load_module('_UTVolumeLibrary', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _UTVolumeLibrary = swig_import_helper()
    del swig_import_helper
else:
    import _UTVolumeLibrary
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class VolumeRenderer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VolumeRenderer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VolumeRenderer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _UTVolumeLibrary.new_VolumeRenderer(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _UTVolumeLibrary.delete_VolumeRenderer
    __del__ = lambda self: None

    def initRenderer(self):
        return _UTVolumeLibrary.VolumeRenderer_initRenderer(self)

    def setAspectRatio(self, ratioX, ratioY, ratioZ):
        return _UTVolumeLibrary.VolumeRenderer_setAspectRatio(self, ratioX, ratioY, ratioZ)

    def setTextureSubCube(self, minX, minY, minZ, maxX, maxY, maxZ):
        return _UTVolumeLibrary.VolumeRenderer_setTextureSubCube(self, minX, minY, minZ, maxX, maxY, maxZ)

    def setQuality(self, quality):
        return _UTVolumeLibrary.VolumeRenderer_setQuality(self, quality)

    def getQuality(self):
        return _UTVolumeLibrary.VolumeRenderer_getQuality(self)

    def setNearPlane(self, nearPlane):
        return _UTVolumeLibrary.VolumeRenderer_setNearPlane(self, nearPlane)

    def getNearPlane(self):
        return _UTVolumeLibrary.VolumeRenderer_getNearPlane(self)

    def isShadedRenderingAvailable(self):
        return _UTVolumeLibrary.VolumeRenderer_isShadedRenderingAvailable(self)

    def enableShadedRendering(self):
        return _UTVolumeLibrary.VolumeRenderer_enableShadedRendering(self)

    def disableShadedRendering(self):
        return _UTVolumeLibrary.VolumeRenderer_disableShadedRendering(self)

    def uploadColorMappedData(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_uploadColorMappedData(self, data, width, height, depth)

    def uploadColorMappedDataWithBorder(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_uploadColorMappedDataWithBorder(self, data, width, height, depth)

    def testColorMappedData(self, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_testColorMappedData(self, width, height, depth)

    def testColorMappedDataWithBorder(self, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_testColorMappedDataWithBorder(self, width, height, depth)

    def uploadRGBAData(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_uploadRGBAData(self, data, width, height, depth)

    def uploadGradients(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_uploadGradients(self, data, width, height, depth)

    def calculateGradientsFromDensities(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_calculateGradientsFromDensities(self, data, width, height, depth)

    def uploadColorMap(self, colorMap):
        return _UTVolumeLibrary.VolumeRenderer_uploadColorMap(self, colorMap)

    def getNumberOfPlanesRendered(self):
        return _UTVolumeLibrary.VolumeRenderer_getNumberOfPlanesRendered(self)

    def renderVolume(self):
        return _UTVolumeLibrary.VolumeRenderer_renderVolume(self)

    def uploadZeroPaddedData(self, data, width, height, depth):
        return _UTVolumeLibrary.VolumeRenderer_uploadZeroPaddedData(self, data, width, height, depth)
VolumeRenderer_swigregister = _UTVolumeLibrary.VolumeRenderer_swigregister
VolumeRenderer_swigregister(VolumeRenderer)


def InitTexParameteri():
    return _UTVolumeLibrary.InitTexParameteri()
InitTexParameteri = _UTVolumeLibrary.InitTexParameteri

def QueryExtension(extName):
    return _UTVolumeLibrary.QueryExtension(extName)
QueryExtension = _UTVolumeLibrary.QueryExtension
# This file is compatible with both classic and new-style classes.

createNumArr = _UTVolumeLibrary.createNumArr

