# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_glulib', [dirname(__file__)])
        except ImportError:
            import _glulib
            return _glulib
        if fp is not None:
            try:
                _mod = imp.load_module('_glulib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _glulib = swig_import_helper()
    del swig_import_helper
else:
    import _glulib
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_glulib.GLU_EXT_object_space_tess_swigconstant(_glulib)
GLU_EXT_object_space_tess = _glulib.GLU_EXT_object_space_tess

_glulib.GLU_EXT_nurbs_tessellator_swigconstant(_glulib)
GLU_EXT_nurbs_tessellator = _glulib.GLU_EXT_nurbs_tessellator

_glulib.GLU_FALSE_swigconstant(_glulib)
GLU_FALSE = _glulib.GLU_FALSE

_glulib.GLU_TRUE_swigconstant(_glulib)
GLU_TRUE = _glulib.GLU_TRUE

_glulib.GLU_VERSION_1_1_swigconstant(_glulib)
GLU_VERSION_1_1 = _glulib.GLU_VERSION_1_1

_glulib.GLU_VERSION_1_2_swigconstant(_glulib)
GLU_VERSION_1_2 = _glulib.GLU_VERSION_1_2

_glulib.GLU_VERSION_1_3_swigconstant(_glulib)
GLU_VERSION_1_3 = _glulib.GLU_VERSION_1_3

_glulib.GLU_VERSION_swigconstant(_glulib)
GLU_VERSION = _glulib.GLU_VERSION

_glulib.GLU_EXTENSIONS_swigconstant(_glulib)
GLU_EXTENSIONS = _glulib.GLU_EXTENSIONS

_glulib.GLU_INVALID_ENUM_swigconstant(_glulib)
GLU_INVALID_ENUM = _glulib.GLU_INVALID_ENUM

_glulib.GLU_INVALID_VALUE_swigconstant(_glulib)
GLU_INVALID_VALUE = _glulib.GLU_INVALID_VALUE

_glulib.GLU_OUT_OF_MEMORY_swigconstant(_glulib)
GLU_OUT_OF_MEMORY = _glulib.GLU_OUT_OF_MEMORY

_glulib.GLU_INCOMPATIBLE_GL_VERSION_swigconstant(_glulib)
GLU_INCOMPATIBLE_GL_VERSION = _glulib.GLU_INCOMPATIBLE_GL_VERSION

_glulib.GLU_INVALID_OPERATION_swigconstant(_glulib)
GLU_INVALID_OPERATION = _glulib.GLU_INVALID_OPERATION

_glulib.GLU_OUTLINE_POLYGON_swigconstant(_glulib)
GLU_OUTLINE_POLYGON = _glulib.GLU_OUTLINE_POLYGON

_glulib.GLU_OUTLINE_PATCH_swigconstant(_glulib)
GLU_OUTLINE_PATCH = _glulib.GLU_OUTLINE_PATCH

_glulib.GLU_NURBS_ERROR_swigconstant(_glulib)
GLU_NURBS_ERROR = _glulib.GLU_NURBS_ERROR

_glulib.GLU_ERROR_swigconstant(_glulib)
GLU_ERROR = _glulib.GLU_ERROR

_glulib.GLU_NURBS_BEGIN_swigconstant(_glulib)
GLU_NURBS_BEGIN = _glulib.GLU_NURBS_BEGIN

_glulib.GLU_NURBS_BEGIN_EXT_swigconstant(_glulib)
GLU_NURBS_BEGIN_EXT = _glulib.GLU_NURBS_BEGIN_EXT

_glulib.GLU_NURBS_VERTEX_swigconstant(_glulib)
GLU_NURBS_VERTEX = _glulib.GLU_NURBS_VERTEX

_glulib.GLU_NURBS_VERTEX_EXT_swigconstant(_glulib)
GLU_NURBS_VERTEX_EXT = _glulib.GLU_NURBS_VERTEX_EXT

_glulib.GLU_NURBS_NORMAL_swigconstant(_glulib)
GLU_NURBS_NORMAL = _glulib.GLU_NURBS_NORMAL

_glulib.GLU_NURBS_NORMAL_EXT_swigconstant(_glulib)
GLU_NURBS_NORMAL_EXT = _glulib.GLU_NURBS_NORMAL_EXT

_glulib.GLU_NURBS_COLOR_swigconstant(_glulib)
GLU_NURBS_COLOR = _glulib.GLU_NURBS_COLOR

_glulib.GLU_NURBS_COLOR_EXT_swigconstant(_glulib)
GLU_NURBS_COLOR_EXT = _glulib.GLU_NURBS_COLOR_EXT

_glulib.GLU_NURBS_TEXTURE_COORD_swigconstant(_glulib)
GLU_NURBS_TEXTURE_COORD = _glulib.GLU_NURBS_TEXTURE_COORD

_glulib.GLU_NURBS_TEX_COORD_EXT_swigconstant(_glulib)
GLU_NURBS_TEX_COORD_EXT = _glulib.GLU_NURBS_TEX_COORD_EXT

_glulib.GLU_NURBS_END_swigconstant(_glulib)
GLU_NURBS_END = _glulib.GLU_NURBS_END

_glulib.GLU_NURBS_END_EXT_swigconstant(_glulib)
GLU_NURBS_END_EXT = _glulib.GLU_NURBS_END_EXT

_glulib.GLU_NURBS_BEGIN_DATA_swigconstant(_glulib)
GLU_NURBS_BEGIN_DATA = _glulib.GLU_NURBS_BEGIN_DATA

_glulib.GLU_NURBS_BEGIN_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_BEGIN_DATA_EXT = _glulib.GLU_NURBS_BEGIN_DATA_EXT

_glulib.GLU_NURBS_VERTEX_DATA_swigconstant(_glulib)
GLU_NURBS_VERTEX_DATA = _glulib.GLU_NURBS_VERTEX_DATA

_glulib.GLU_NURBS_VERTEX_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_VERTEX_DATA_EXT = _glulib.GLU_NURBS_VERTEX_DATA_EXT

_glulib.GLU_NURBS_NORMAL_DATA_swigconstant(_glulib)
GLU_NURBS_NORMAL_DATA = _glulib.GLU_NURBS_NORMAL_DATA

_glulib.GLU_NURBS_NORMAL_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_NORMAL_DATA_EXT = _glulib.GLU_NURBS_NORMAL_DATA_EXT

_glulib.GLU_NURBS_COLOR_DATA_swigconstant(_glulib)
GLU_NURBS_COLOR_DATA = _glulib.GLU_NURBS_COLOR_DATA

_glulib.GLU_NURBS_COLOR_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_COLOR_DATA_EXT = _glulib.GLU_NURBS_COLOR_DATA_EXT

_glulib.GLU_NURBS_TEXTURE_COORD_DATA_swigconstant(_glulib)
GLU_NURBS_TEXTURE_COORD_DATA = _glulib.GLU_NURBS_TEXTURE_COORD_DATA

_glulib.GLU_NURBS_TEX_COORD_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_TEX_COORD_DATA_EXT = _glulib.GLU_NURBS_TEX_COORD_DATA_EXT

_glulib.GLU_NURBS_END_DATA_swigconstant(_glulib)
GLU_NURBS_END_DATA = _glulib.GLU_NURBS_END_DATA

_glulib.GLU_NURBS_END_DATA_EXT_swigconstant(_glulib)
GLU_NURBS_END_DATA_EXT = _glulib.GLU_NURBS_END_DATA_EXT

_glulib.GLU_NURBS_ERROR1_swigconstant(_glulib)
GLU_NURBS_ERROR1 = _glulib.GLU_NURBS_ERROR1

_glulib.GLU_NURBS_ERROR2_swigconstant(_glulib)
GLU_NURBS_ERROR2 = _glulib.GLU_NURBS_ERROR2

_glulib.GLU_NURBS_ERROR3_swigconstant(_glulib)
GLU_NURBS_ERROR3 = _glulib.GLU_NURBS_ERROR3

_glulib.GLU_NURBS_ERROR4_swigconstant(_glulib)
GLU_NURBS_ERROR4 = _glulib.GLU_NURBS_ERROR4

_glulib.GLU_NURBS_ERROR5_swigconstant(_glulib)
GLU_NURBS_ERROR5 = _glulib.GLU_NURBS_ERROR5

_glulib.GLU_NURBS_ERROR6_swigconstant(_glulib)
GLU_NURBS_ERROR6 = _glulib.GLU_NURBS_ERROR6

_glulib.GLU_NURBS_ERROR7_swigconstant(_glulib)
GLU_NURBS_ERROR7 = _glulib.GLU_NURBS_ERROR7

_glulib.GLU_NURBS_ERROR8_swigconstant(_glulib)
GLU_NURBS_ERROR8 = _glulib.GLU_NURBS_ERROR8

_glulib.GLU_NURBS_ERROR9_swigconstant(_glulib)
GLU_NURBS_ERROR9 = _glulib.GLU_NURBS_ERROR9

_glulib.GLU_NURBS_ERROR10_swigconstant(_glulib)
GLU_NURBS_ERROR10 = _glulib.GLU_NURBS_ERROR10

_glulib.GLU_NURBS_ERROR11_swigconstant(_glulib)
GLU_NURBS_ERROR11 = _glulib.GLU_NURBS_ERROR11

_glulib.GLU_NURBS_ERROR12_swigconstant(_glulib)
GLU_NURBS_ERROR12 = _glulib.GLU_NURBS_ERROR12

_glulib.GLU_NURBS_ERROR13_swigconstant(_glulib)
GLU_NURBS_ERROR13 = _glulib.GLU_NURBS_ERROR13

_glulib.GLU_NURBS_ERROR14_swigconstant(_glulib)
GLU_NURBS_ERROR14 = _glulib.GLU_NURBS_ERROR14

_glulib.GLU_NURBS_ERROR15_swigconstant(_glulib)
GLU_NURBS_ERROR15 = _glulib.GLU_NURBS_ERROR15

_glulib.GLU_NURBS_ERROR16_swigconstant(_glulib)
GLU_NURBS_ERROR16 = _glulib.GLU_NURBS_ERROR16

_glulib.GLU_NURBS_ERROR17_swigconstant(_glulib)
GLU_NURBS_ERROR17 = _glulib.GLU_NURBS_ERROR17

_glulib.GLU_NURBS_ERROR18_swigconstant(_glulib)
GLU_NURBS_ERROR18 = _glulib.GLU_NURBS_ERROR18

_glulib.GLU_NURBS_ERROR19_swigconstant(_glulib)
GLU_NURBS_ERROR19 = _glulib.GLU_NURBS_ERROR19

_glulib.GLU_NURBS_ERROR20_swigconstant(_glulib)
GLU_NURBS_ERROR20 = _glulib.GLU_NURBS_ERROR20

_glulib.GLU_NURBS_ERROR21_swigconstant(_glulib)
GLU_NURBS_ERROR21 = _glulib.GLU_NURBS_ERROR21

_glulib.GLU_NURBS_ERROR22_swigconstant(_glulib)
GLU_NURBS_ERROR22 = _glulib.GLU_NURBS_ERROR22

_glulib.GLU_NURBS_ERROR23_swigconstant(_glulib)
GLU_NURBS_ERROR23 = _glulib.GLU_NURBS_ERROR23

_glulib.GLU_NURBS_ERROR24_swigconstant(_glulib)
GLU_NURBS_ERROR24 = _glulib.GLU_NURBS_ERROR24

_glulib.GLU_NURBS_ERROR25_swigconstant(_glulib)
GLU_NURBS_ERROR25 = _glulib.GLU_NURBS_ERROR25

_glulib.GLU_NURBS_ERROR26_swigconstant(_glulib)
GLU_NURBS_ERROR26 = _glulib.GLU_NURBS_ERROR26

_glulib.GLU_NURBS_ERROR27_swigconstant(_glulib)
GLU_NURBS_ERROR27 = _glulib.GLU_NURBS_ERROR27

_glulib.GLU_NURBS_ERROR28_swigconstant(_glulib)
GLU_NURBS_ERROR28 = _glulib.GLU_NURBS_ERROR28

_glulib.GLU_NURBS_ERROR29_swigconstant(_glulib)
GLU_NURBS_ERROR29 = _glulib.GLU_NURBS_ERROR29

_glulib.GLU_NURBS_ERROR30_swigconstant(_glulib)
GLU_NURBS_ERROR30 = _glulib.GLU_NURBS_ERROR30

_glulib.GLU_NURBS_ERROR31_swigconstant(_glulib)
GLU_NURBS_ERROR31 = _glulib.GLU_NURBS_ERROR31

_glulib.GLU_NURBS_ERROR32_swigconstant(_glulib)
GLU_NURBS_ERROR32 = _glulib.GLU_NURBS_ERROR32

_glulib.GLU_NURBS_ERROR33_swigconstant(_glulib)
GLU_NURBS_ERROR33 = _glulib.GLU_NURBS_ERROR33

_glulib.GLU_NURBS_ERROR34_swigconstant(_glulib)
GLU_NURBS_ERROR34 = _glulib.GLU_NURBS_ERROR34

_glulib.GLU_NURBS_ERROR35_swigconstant(_glulib)
GLU_NURBS_ERROR35 = _glulib.GLU_NURBS_ERROR35

_glulib.GLU_NURBS_ERROR36_swigconstant(_glulib)
GLU_NURBS_ERROR36 = _glulib.GLU_NURBS_ERROR36

_glulib.GLU_NURBS_ERROR37_swigconstant(_glulib)
GLU_NURBS_ERROR37 = _glulib.GLU_NURBS_ERROR37

_glulib.GLU_AUTO_LOAD_MATRIX_swigconstant(_glulib)
GLU_AUTO_LOAD_MATRIX = _glulib.GLU_AUTO_LOAD_MATRIX

_glulib.GLU_CULLING_swigconstant(_glulib)
GLU_CULLING = _glulib.GLU_CULLING

_glulib.GLU_SAMPLING_TOLERANCE_swigconstant(_glulib)
GLU_SAMPLING_TOLERANCE = _glulib.GLU_SAMPLING_TOLERANCE

_glulib.GLU_DISPLAY_MODE_swigconstant(_glulib)
GLU_DISPLAY_MODE = _glulib.GLU_DISPLAY_MODE

_glulib.GLU_PARAMETRIC_TOLERANCE_swigconstant(_glulib)
GLU_PARAMETRIC_TOLERANCE = _glulib.GLU_PARAMETRIC_TOLERANCE

_glulib.GLU_SAMPLING_METHOD_swigconstant(_glulib)
GLU_SAMPLING_METHOD = _glulib.GLU_SAMPLING_METHOD

_glulib.GLU_U_STEP_swigconstant(_glulib)
GLU_U_STEP = _glulib.GLU_U_STEP

_glulib.GLU_V_STEP_swigconstant(_glulib)
GLU_V_STEP = _glulib.GLU_V_STEP

_glulib.GLU_NURBS_MODE_swigconstant(_glulib)
GLU_NURBS_MODE = _glulib.GLU_NURBS_MODE

_glulib.GLU_NURBS_MODE_EXT_swigconstant(_glulib)
GLU_NURBS_MODE_EXT = _glulib.GLU_NURBS_MODE_EXT

_glulib.GLU_NURBS_TESSELLATOR_swigconstant(_glulib)
GLU_NURBS_TESSELLATOR = _glulib.GLU_NURBS_TESSELLATOR

_glulib.GLU_NURBS_TESSELLATOR_EXT_swigconstant(_glulib)
GLU_NURBS_TESSELLATOR_EXT = _glulib.GLU_NURBS_TESSELLATOR_EXT

_glulib.GLU_NURBS_RENDERER_swigconstant(_glulib)
GLU_NURBS_RENDERER = _glulib.GLU_NURBS_RENDERER

_glulib.GLU_NURBS_RENDERER_EXT_swigconstant(_glulib)
GLU_NURBS_RENDERER_EXT = _glulib.GLU_NURBS_RENDERER_EXT

_glulib.GLU_OBJECT_PARAMETRIC_ERROR_swigconstant(_glulib)
GLU_OBJECT_PARAMETRIC_ERROR = _glulib.GLU_OBJECT_PARAMETRIC_ERROR

_glulib.GLU_OBJECT_PARAMETRIC_ERROR_EXT_swigconstant(_glulib)
GLU_OBJECT_PARAMETRIC_ERROR_EXT = _glulib.GLU_OBJECT_PARAMETRIC_ERROR_EXT

_glulib.GLU_OBJECT_PATH_LENGTH_swigconstant(_glulib)
GLU_OBJECT_PATH_LENGTH = _glulib.GLU_OBJECT_PATH_LENGTH

_glulib.GLU_OBJECT_PATH_LENGTH_EXT_swigconstant(_glulib)
GLU_OBJECT_PATH_LENGTH_EXT = _glulib.GLU_OBJECT_PATH_LENGTH_EXT

_glulib.GLU_PATH_LENGTH_swigconstant(_glulib)
GLU_PATH_LENGTH = _glulib.GLU_PATH_LENGTH

_glulib.GLU_PARAMETRIC_ERROR_swigconstant(_glulib)
GLU_PARAMETRIC_ERROR = _glulib.GLU_PARAMETRIC_ERROR

_glulib.GLU_DOMAIN_DISTANCE_swigconstant(_glulib)
GLU_DOMAIN_DISTANCE = _glulib.GLU_DOMAIN_DISTANCE

_glulib.GLU_MAP1_TRIM_2_swigconstant(_glulib)
GLU_MAP1_TRIM_2 = _glulib.GLU_MAP1_TRIM_2

_glulib.GLU_MAP1_TRIM_3_swigconstant(_glulib)
GLU_MAP1_TRIM_3 = _glulib.GLU_MAP1_TRIM_3

_glulib.GLU_POINT_swigconstant(_glulib)
GLU_POINT = _glulib.GLU_POINT

_glulib.GLU_LINE_swigconstant(_glulib)
GLU_LINE = _glulib.GLU_LINE

_glulib.GLU_FILL_swigconstant(_glulib)
GLU_FILL = _glulib.GLU_FILL

_glulib.GLU_SILHOUETTE_swigconstant(_glulib)
GLU_SILHOUETTE = _glulib.GLU_SILHOUETTE

_glulib.GLU_SMOOTH_swigconstant(_glulib)
GLU_SMOOTH = _glulib.GLU_SMOOTH

_glulib.GLU_FLAT_swigconstant(_glulib)
GLU_FLAT = _glulib.GLU_FLAT

_glulib.GLU_NONE_swigconstant(_glulib)
GLU_NONE = _glulib.GLU_NONE

_glulib.GLU_OUTSIDE_swigconstant(_glulib)
GLU_OUTSIDE = _glulib.GLU_OUTSIDE

_glulib.GLU_INSIDE_swigconstant(_glulib)
GLU_INSIDE = _glulib.GLU_INSIDE

_glulib.GLU_TESS_BEGIN_swigconstant(_glulib)
GLU_TESS_BEGIN = _glulib.GLU_TESS_BEGIN

_glulib.GLU_BEGIN_swigconstant(_glulib)
GLU_BEGIN = _glulib.GLU_BEGIN

_glulib.GLU_TESS_VERTEX_swigconstant(_glulib)
GLU_TESS_VERTEX = _glulib.GLU_TESS_VERTEX

_glulib.GLU_VERTEX_swigconstant(_glulib)
GLU_VERTEX = _glulib.GLU_VERTEX

_glulib.GLU_TESS_END_swigconstant(_glulib)
GLU_TESS_END = _glulib.GLU_TESS_END

_glulib.GLU_END_swigconstant(_glulib)
GLU_END = _glulib.GLU_END

_glulib.GLU_TESS_ERROR_swigconstant(_glulib)
GLU_TESS_ERROR = _glulib.GLU_TESS_ERROR

_glulib.GLU_TESS_EDGE_FLAG_swigconstant(_glulib)
GLU_TESS_EDGE_FLAG = _glulib.GLU_TESS_EDGE_FLAG

_glulib.GLU_EDGE_FLAG_swigconstant(_glulib)
GLU_EDGE_FLAG = _glulib.GLU_EDGE_FLAG

_glulib.GLU_TESS_COMBINE_swigconstant(_glulib)
GLU_TESS_COMBINE = _glulib.GLU_TESS_COMBINE

_glulib.GLU_TESS_BEGIN_DATA_swigconstant(_glulib)
GLU_TESS_BEGIN_DATA = _glulib.GLU_TESS_BEGIN_DATA

_glulib.GLU_TESS_VERTEX_DATA_swigconstant(_glulib)
GLU_TESS_VERTEX_DATA = _glulib.GLU_TESS_VERTEX_DATA

_glulib.GLU_TESS_END_DATA_swigconstant(_glulib)
GLU_TESS_END_DATA = _glulib.GLU_TESS_END_DATA

_glulib.GLU_TESS_ERROR_DATA_swigconstant(_glulib)
GLU_TESS_ERROR_DATA = _glulib.GLU_TESS_ERROR_DATA

_glulib.GLU_TESS_EDGE_FLAG_DATA_swigconstant(_glulib)
GLU_TESS_EDGE_FLAG_DATA = _glulib.GLU_TESS_EDGE_FLAG_DATA

_glulib.GLU_TESS_COMBINE_DATA_swigconstant(_glulib)
GLU_TESS_COMBINE_DATA = _glulib.GLU_TESS_COMBINE_DATA

_glulib.GLU_CW_swigconstant(_glulib)
GLU_CW = _glulib.GLU_CW

_glulib.GLU_CCW_swigconstant(_glulib)
GLU_CCW = _glulib.GLU_CCW

_glulib.GLU_INTERIOR_swigconstant(_glulib)
GLU_INTERIOR = _glulib.GLU_INTERIOR

_glulib.GLU_EXTERIOR_swigconstant(_glulib)
GLU_EXTERIOR = _glulib.GLU_EXTERIOR

_glulib.GLU_UNKNOWN_swigconstant(_glulib)
GLU_UNKNOWN = _glulib.GLU_UNKNOWN

_glulib.GLU_TESS_WINDING_RULE_swigconstant(_glulib)
GLU_TESS_WINDING_RULE = _glulib.GLU_TESS_WINDING_RULE

_glulib.GLU_TESS_BOUNDARY_ONLY_swigconstant(_glulib)
GLU_TESS_BOUNDARY_ONLY = _glulib.GLU_TESS_BOUNDARY_ONLY

_glulib.GLU_TESS_TOLERANCE_swigconstant(_glulib)
GLU_TESS_TOLERANCE = _glulib.GLU_TESS_TOLERANCE

_glulib.GLU_TESS_ERROR1_swigconstant(_glulib)
GLU_TESS_ERROR1 = _glulib.GLU_TESS_ERROR1

_glulib.GLU_TESS_ERROR2_swigconstant(_glulib)
GLU_TESS_ERROR2 = _glulib.GLU_TESS_ERROR2

_glulib.GLU_TESS_ERROR3_swigconstant(_glulib)
GLU_TESS_ERROR3 = _glulib.GLU_TESS_ERROR3

_glulib.GLU_TESS_ERROR4_swigconstant(_glulib)
GLU_TESS_ERROR4 = _glulib.GLU_TESS_ERROR4

_glulib.GLU_TESS_ERROR5_swigconstant(_glulib)
GLU_TESS_ERROR5 = _glulib.GLU_TESS_ERROR5

_glulib.GLU_TESS_ERROR6_swigconstant(_glulib)
GLU_TESS_ERROR6 = _glulib.GLU_TESS_ERROR6

_glulib.GLU_TESS_ERROR7_swigconstant(_glulib)
GLU_TESS_ERROR7 = _glulib.GLU_TESS_ERROR7

_glulib.GLU_TESS_ERROR8_swigconstant(_glulib)
GLU_TESS_ERROR8 = _glulib.GLU_TESS_ERROR8

_glulib.GLU_TESS_MISSING_BEGIN_POLYGON_swigconstant(_glulib)
GLU_TESS_MISSING_BEGIN_POLYGON = _glulib.GLU_TESS_MISSING_BEGIN_POLYGON

_glulib.GLU_TESS_MISSING_BEGIN_CONTOUR_swigconstant(_glulib)
GLU_TESS_MISSING_BEGIN_CONTOUR = _glulib.GLU_TESS_MISSING_BEGIN_CONTOUR

_glulib.GLU_TESS_MISSING_END_POLYGON_swigconstant(_glulib)
GLU_TESS_MISSING_END_POLYGON = _glulib.GLU_TESS_MISSING_END_POLYGON

_glulib.GLU_TESS_MISSING_END_CONTOUR_swigconstant(_glulib)
GLU_TESS_MISSING_END_CONTOUR = _glulib.GLU_TESS_MISSING_END_CONTOUR

_glulib.GLU_TESS_COORD_TOO_LARGE_swigconstant(_glulib)
GLU_TESS_COORD_TOO_LARGE = _glulib.GLU_TESS_COORD_TOO_LARGE

_glulib.GLU_TESS_NEED_COMBINE__swigconstant(_glulib)
GLU_TESS_NEED_COMBINE_ = _glulib.GLU_TESS_NEED_COMBINE_

_glulib.GLU_TESS_WINDING_ODD_swigconstant(_glulib)
GLU_TESS_WINDING_ODD = _glulib.GLU_TESS_WINDING_ODD

_glulib.GLU_TESS_WINDING_NONZERO_swigconstant(_glulib)
GLU_TESS_WINDING_NONZERO = _glulib.GLU_TESS_WINDING_NONZERO

_glulib.GLU_TESS_WINDING_POSITIVE_swigconstant(_glulib)
GLU_TESS_WINDING_POSITIVE = _glulib.GLU_TESS_WINDING_POSITIVE

_glulib.GLU_TESS_WINDING_NEGATIVE_swigconstant(_glulib)
GLU_TESS_WINDING_NEGATIVE = _glulib.GLU_TESS_WINDING_NEGATIVE

_glulib.GLU_TESS_WINDING_ABS_GEQ_TWO_swigconstant(_glulib)
GLU_TESS_WINDING_ABS_GEQ_TWO = _glulib.GLU_TESS_WINDING_ABS_GEQ_TWO

_glulib.GLU_TESS_MAX_COORD_swigconstant(_glulib)
GLU_TESS_MAX_COORD = _glulib.GLU_TESS_MAX_COORD

def gluBeginCurve(nurb):
    return _glulib.gluBeginCurve(nurb)
gluBeginCurve = _glulib.gluBeginCurve

def gluBeginPolygon(tess):
    return _glulib.gluBeginPolygon(tess)
gluBeginPolygon = _glulib.gluBeginPolygon

def gluBeginSurface(nurb):
    return _glulib.gluBeginSurface(nurb)
gluBeginSurface = _glulib.gluBeginSurface

def gluBeginTrim(nurb):
    return _glulib.gluBeginTrim(nurb)
gluBeginTrim = _glulib.gluBeginTrim

def gluBuild1DMipmapLevels(target, internalFormat, width, format, type, level, base, max, data):
    return _glulib.gluBuild1DMipmapLevels(target, internalFormat, width, format, type, level, base, max, data)
gluBuild1DMipmapLevels = _glulib.gluBuild1DMipmapLevels

def gluBuild1DMipmaps(target, internalFormat, width, format, type, data):
    return _glulib.gluBuild1DMipmaps(target, internalFormat, width, format, type, data)
gluBuild1DMipmaps = _glulib.gluBuild1DMipmaps

def gluBuild2DMipmapLevels(target, internalFormat, width, height, format, type, level, base, max, data):
    return _glulib.gluBuild2DMipmapLevels(target, internalFormat, width, height, format, type, level, base, max, data)
gluBuild2DMipmapLevels = _glulib.gluBuild2DMipmapLevels

def gluBuild2DMipmaps(target, internalFormat, width, height, format, type, data):
    return _glulib.gluBuild2DMipmaps(target, internalFormat, width, height, format, type, data)
gluBuild2DMipmaps = _glulib.gluBuild2DMipmaps

def gluBuild3DMipmapLevels(target, internalFormat, width, height, depth, format, type, level, base, max, data):
    return _glulib.gluBuild3DMipmapLevels(target, internalFormat, width, height, depth, format, type, level, base, max, data)
gluBuild3DMipmapLevels = _glulib.gluBuild3DMipmapLevels

def gluBuild3DMipmaps(target, internalFormat, width, height, depth, format, type, data):
    return _glulib.gluBuild3DMipmaps(target, internalFormat, width, height, depth, format, type, data)
gluBuild3DMipmaps = _glulib.gluBuild3DMipmaps

def gluCheckExtension(extName, extString):
    return _glulib.gluCheckExtension(extName, extString)
gluCheckExtension = _glulib.gluCheckExtension

def gluCylinder(quad, base, top, height, slices, stacks):
    return _glulib.gluCylinder(quad, base, top, height, slices, stacks)
gluCylinder = _glulib.gluCylinder

def gluDeleteNurbsRenderer(nurb):
    return _glulib.gluDeleteNurbsRenderer(nurb)
gluDeleteNurbsRenderer = _glulib.gluDeleteNurbsRenderer

def gluDeleteQuadric(quad):
    return _glulib.gluDeleteQuadric(quad)
gluDeleteQuadric = _glulib.gluDeleteQuadric

def gluDeleteTess(tess):
    return _glulib.gluDeleteTess(tess)
gluDeleteTess = _glulib.gluDeleteTess

def gluDisk(quad, inner, outer, slices, loops):
    return _glulib.gluDisk(quad, inner, outer, slices, loops)
gluDisk = _glulib.gluDisk

def gluEndCurve(nurb):
    return _glulib.gluEndCurve(nurb)
gluEndCurve = _glulib.gluEndCurve

def gluEndPolygon(tess):
    return _glulib.gluEndPolygon(tess)
gluEndPolygon = _glulib.gluEndPolygon

def gluEndSurface(nurb):
    return _glulib.gluEndSurface(nurb)
gluEndSurface = _glulib.gluEndSurface

def gluEndTrim(nurb):
    return _glulib.gluEndTrim(nurb)
gluEndTrim = _glulib.gluEndTrim

def gluGetNurbsProperty(nurb, property, data):
    return _glulib.gluGetNurbsProperty(nurb, property, data)
gluGetNurbsProperty = _glulib.gluGetNurbsProperty

def gluGetString(name):
    return _glulib.gluGetString(name)
gluGetString = _glulib.gluGetString

def gluGetTessProperty(tess, which, data):
    return _glulib.gluGetTessProperty(tess, which, data)
gluGetTessProperty = _glulib.gluGetTessProperty

def gluLoadSamplingMatrices(nurb, model, perspective, view):
    return _glulib.gluLoadSamplingMatrices(nurb, model, perspective, view)
gluLoadSamplingMatrices = _glulib.gluLoadSamplingMatrices

def gluLookAt(eyeX, eyeY, eyeZ, centerX, centerY, centerZ, upX, upY, upZ):
    return _glulib.gluLookAt(eyeX, eyeY, eyeZ, centerX, centerY, centerZ, upX, upY, upZ)
gluLookAt = _glulib.gluLookAt

def gluNewNurbsRenderer():
    return _glulib.gluNewNurbsRenderer()
gluNewNurbsRenderer = _glulib.gluNewNurbsRenderer

def gluNewQuadric():
    return _glulib.gluNewQuadric()
gluNewQuadric = _glulib.gluNewQuadric

def gluNewTess():
    return _glulib.gluNewTess()
gluNewTess = _glulib.gluNewTess

def gluNextContour(tess, type):
    return _glulib.gluNextContour(tess, type)
gluNextContour = _glulib.gluNextContour

def gluNurbsCallback(*args):
    return _glulib.gluNurbsCallback(*args)
gluNurbsCallback = _glulib.gluNurbsCallback

def gluNurbsCallbackData(nurb, userData):
    return _glulib.gluNurbsCallbackData(nurb, userData)
gluNurbsCallbackData = _glulib.gluNurbsCallbackData

def gluNurbsCallbackDataEXT(nurb, userData):
    return _glulib.gluNurbsCallbackDataEXT(nurb, userData)
gluNurbsCallbackDataEXT = _glulib.gluNurbsCallbackDataEXT

def gluNurbsCurve(nurb, knotCount, knots, stride, control, order, type):
    return _glulib.gluNurbsCurve(nurb, knotCount, knots, stride, control, order, type)
gluNurbsCurve = _glulib.gluNurbsCurve

def gluNurbsProperty(nurb, property, value):
    return _glulib.gluNurbsProperty(nurb, property, value)
gluNurbsProperty = _glulib.gluNurbsProperty

def gluNurbsSurface(nurb, sKnotCount, sKnots, tKnotCount, tKnots, sStride, tStride, control, sOrder, tOrder, type):
    return _glulib.gluNurbsSurface(nurb, sKnotCount, sKnots, tKnotCount, tKnots, sStride, tStride, control, sOrder, tOrder, type)
gluNurbsSurface = _glulib.gluNurbsSurface

def gluOrtho2D(left, right, bottom, top):
    return _glulib.gluOrtho2D(left, right, bottom, top)
gluOrtho2D = _glulib.gluOrtho2D

def gluPartialDisk(quad, inner, outer, slices, loops, start, sweep):
    return _glulib.gluPartialDisk(quad, inner, outer, slices, loops, start, sweep)
gluPartialDisk = _glulib.gluPartialDisk

def gluPerspective(fovy, aspect, zNear, zFar):
    return _glulib.gluPerspective(fovy, aspect, zNear, zFar)
gluPerspective = _glulib.gluPerspective

def gluPickMatrix(x, y, delX, delY, xxx):
    return _glulib.gluPickMatrix(x, y, delX, delY, xxx)
gluPickMatrix = _glulib.gluPickMatrix

def gluProject(objX, objY, objZ, arg4, arg5, arg6, winX, winY, winZ):
    return _glulib.gluProject(objX, objY, objZ, arg4, arg5, arg6, winX, winY, winZ)
gluProject = _glulib.gluProject

def gluPwlCurve(nurb, count, data, stride, type):
    return _glulib.gluPwlCurve(nurb, count, data, stride, type)
gluPwlCurve = _glulib.gluPwlCurve

def gluQuadricCallback(*args):
    return _glulib.gluQuadricCallback(*args)
gluQuadricCallback = _glulib.gluQuadricCallback

def gluQuadricDrawStyle(quad, draw):
    return _glulib.gluQuadricDrawStyle(quad, draw)
gluQuadricDrawStyle = _glulib.gluQuadricDrawStyle

def gluQuadricNormals(quad, normal):
    return _glulib.gluQuadricNormals(quad, normal)
gluQuadricNormals = _glulib.gluQuadricNormals

def gluQuadricOrientation(quad, orientation):
    return _glulib.gluQuadricOrientation(quad, orientation)
gluQuadricOrientation = _glulib.gluQuadricOrientation

def gluQuadricTexture(quad, texture):
    return _glulib.gluQuadricTexture(quad, texture)
gluQuadricTexture = _glulib.gluQuadricTexture

def gluScaleImage(format, wIn, hIn, typeIn, dataIn, wOut, hOut, typeOut, dataOut):
    return _glulib.gluScaleImage(format, wIn, hIn, typeIn, dataIn, wOut, hOut, typeOut, dataOut)
gluScaleImage = _glulib.gluScaleImage

def gluSphere(quad, radius, slices, stacks):
    return _glulib.gluSphere(quad, radius, slices, stacks)
gluSphere = _glulib.gluSphere

def gluTessBeginContour(tess):
    return _glulib.gluTessBeginContour(tess)
gluTessBeginContour = _glulib.gluTessBeginContour

def gluTessBeginPolygon(tess, data):
    return _glulib.gluTessBeginPolygon(tess, data)
gluTessBeginPolygon = _glulib.gluTessBeginPolygon

def gluTessCallback(*args):
    return _glulib.gluTessCallback(*args)
gluTessCallback = _glulib.gluTessCallback

def gluTessEndContour(tess):
    return _glulib.gluTessEndContour(tess)
gluTessEndContour = _glulib.gluTessEndContour

def gluTessEndPolygon(tess):
    return _glulib.gluTessEndPolygon(tess)
gluTessEndPolygon = _glulib.gluTessEndPolygon

def gluTessNormal(tess, valueX, valueY, valueZ):
    return _glulib.gluTessNormal(tess, valueX, valueY, valueZ)
gluTessNormal = _glulib.gluTessNormal

def gluTessProperty(tess, which, data):
    return _glulib.gluTessProperty(tess, which, data)
gluTessProperty = _glulib.gluTessProperty

def gluTessVertex(tess, location, data):
    return _glulib.gluTessVertex(tess, location, data)
gluTessVertex = _glulib.gluTessVertex

def gluUnProject(winX, winY, winZ, arg4, arg5, arg6, objX, objY, objZ):
    return _glulib.gluUnProject(winX, winY, winZ, arg4, arg5, arg6, objX, objY, objZ)
gluUnProject = _glulib.gluUnProject

def gluUnProject4(winX, winY, winZ, clipW, model, proj, view, nearVal, farVal, objX, objY, objZ, objW):
    return _glulib.gluUnProject4(winX, winY, winZ, clipW, model, proj, view, nearVal, farVal, objX, objY, objZ, objW)
gluUnProject4 = _glulib.gluUnProject4
# This file is compatible with both classic and new-style classes.

cvar = _glulib.cvar
gluErrorString = _glulib.gluErrorString

